// Copiright 2023 Carlo Sala (@carlosala)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define NKRO_DEFAULT_ON true
#define PERMISSIVE_HOLD
#define TAPPING_TERM 150
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define MASTER_LEFT

#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#endif
